#!/bin/bash

URL=https://github.com/libbpf/bpftool.git

rm -rf bpftool
git clone ${URL}

cd bpftool
if [ "$#" -ge 1 ]; then
git fetch --depth=1 origin $1 || {
    echo "commit $1 does not exists in ${URL}"
    exit 1
}
git checkout $1
fi

git submodule update --init --recursive

cd src
make -j9
